// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/sharanrprasad/iam-service/internal/dtos"
	"github.com/sharanrprasad/iam-service/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthService is an autogenerated mock type for the authService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Authorize(ctx context.Context, in service.AuthorizeInput) (service.AuthorizeResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 service.AuthorizeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.AuthorizeInput) (service.AuthorizeResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.AuthorizeInput) service.AuthorizeResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(service.AuthorizeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.AuthorizeInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockAuthService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.AuthorizeInput
func (_e *MockAuthService_Expecter) Authorize(ctx any, in any) *MockAuthService_Authorize_Call {
	return &MockAuthService_Authorize_Call{Call: _e.mock.On("Authorize", ctx, in)}
}

func (_c *MockAuthService_Authorize_Call) Run(run func(ctx context.Context, in service.AuthorizeInput)) *MockAuthService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.AuthorizeInput
		if args[1] != nil {
			arg1 = args[1].(service.AuthorizeInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Authorize_Call) Return(authorizeResult service.AuthorizeResult, err error) *MockAuthService_Authorize_Call {
	_c.Call.Return(authorizeResult, err)
	return _c
}

func (_c *MockAuthService_Authorize_Call) RunAndReturn(run func(ctx context.Context, in service.AuthorizeInput) (service.AuthorizeResult, error)) *MockAuthService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, r dtos.LoginRequest) (*service.LoginResult, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *service.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest) (*service.LoginResult, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest) *service.LoginResult); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dtos.LoginRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - r dtos.LoginRequest
func (_e *MockAuthService_Expecter) Login(ctx any, r any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, r)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, r dtos.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(loginResult *service.LoginResult, err error) *MockAuthService_Login_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, r dtos.LoginRequest) (*service.LoginResult, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) Logout(ctx any, sessionID any) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (*dtos.RefreshResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dtos.RefreshResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dtos.RefreshResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dtos.RefreshResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.RefreshResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshToken(ctx any, refreshToken any) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(refreshResponse *dtos.RefreshResponse, err error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(refreshResponse, err)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*dtos.RefreshResponse, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClientService is an autogenerated mock type for the clientService type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// RegisterClient provides a mock function for the type MockClientService
func (_mock *MockClientService) RegisterClient(ctx context.Context, r dtos.RegisterClientRequest) (*dtos.RegisterClientResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 *dtos.RegisterClientResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.RegisterClientRequest) (*dtos.RegisterClientResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.RegisterClientRequest) *dtos.RegisterClientResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.RegisterClientResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dtos.RegisterClientRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientService_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockClientService_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - r dtos.RegisterClientRequest
func (_e *MockClientService_Expecter) RegisterClient(ctx any, r any) *MockClientService_RegisterClient_Call {
	return &MockClientService_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ctx, r)}
}

func (_c *MockClientService_RegisterClient_Call) Run(run func(ctx context.Context, r dtos.RegisterClientRequest)) *MockClientService_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.RegisterClientRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.RegisterClientRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientService_RegisterClient_Call) Return(registerClientResponse *dtos.RegisterClientResponse, err error) *MockClientService_RegisterClient_Call {
	_c.Call.Return(registerClientResponse, err)
	return _c
}

func (_c *MockClientService_RegisterClient_Call) RunAndReturn(run func(ctx context.Context, r dtos.RegisterClientRequest) (*dtos.RegisterClientResponse, error)) *MockClientService_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGrantService creates a new instance of MockTokenGrantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGrantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGrantService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTokenGrantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTokenGrantService is an autogenerated mock type for the tokenGrantService type
type MockTokenGrantService struct {
	mock.Mock
}

type MockTokenGrantService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGrantService) EXPECT() *MockTokenGrantService_Expecter {
	return &MockTokenGrantService_Expecter{mock: &_m.Mock}
}

// Exchange provides a mock function for the type MockTokenGrantService
func (_mock *MockTokenGrantService) Exchange(ctx context.Context, req dtos.TokenRequest) (*dtos.TokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *dtos.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.TokenRequest) (*dtos.TokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.TokenRequest) *dtos.TokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dtos.TokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGrantService_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockTokenGrantService_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - req dtos.TokenRequest
func (_e *MockTokenGrantService_Expecter) Exchange(ctx any, req any) *MockTokenGrantService_Exchange_Call {
	return &MockTokenGrantService_Exchange_Call{Call: _e.mock.On("Exchange", ctx, req)}
}

func (_c *MockTokenGrantService_Exchange_Call) Run(run func(ctx context.Context, req dtos.TokenRequest)) *MockTokenGrantService_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.TokenRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.TokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenGrantService_Exchange_Call) Return(tokenResponse *dtos.TokenResponse, err error) *MockTokenGrantService_Exchange_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockTokenGrantService_Exchange_Call) RunAndReturn(run func(ctx context.Context, req dtos.TokenRequest) (*dtos.TokenResponse, error)) *MockTokenGrantService_Exchange_Call {
	_c.Call.Return(run)
	return _c
}
