// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	"github.com/sharanrprasad/iam-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserRepo is an autogenerated mock type for the userRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(ctx context.Context, u *models.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *models.User
func (_e *MockUserRepo_Expecter) Create(ctx any, u any) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(ctx context.Context, u *models.User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(err error) *MockUserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, u *models.User) error) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) GetByEmail(ctx any, email any) *MockUserRepo_GetByEmail_Call {
	return &MockUserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepo_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) Return(user *models.User, err error) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByID(ctx context.Context, id string) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) GetByID(ctx any, id any) *MockUserRepo_GetByID_Call {
	return &MockUserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByID_Call) Return(user *models.User, err error) *MockUserRepo_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.User, error)) *MockUserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientRepo creates a new instance of MockClientRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClientRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClientRepo is an autogenerated mock type for the clientRepo type
type MockClientRepo struct {
	mock.Mock
}

type MockClientRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepo) EXPECT() *MockClientRepo_Expecter {
	return &MockClientRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientRepo
func (_mock *MockClientRepo) Create(ctx context.Context, c *models.Client) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Client) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c *models.Client
func (_e *MockClientRepo_Expecter) Create(ctx any, c any) *MockClientRepo_Create_Call {
	return &MockClientRepo_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockClientRepo_Create_Call) Run(run func(ctx context.Context, c *models.Client)) *MockClientRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Client
		if args[1] != nil {
			arg1 = args[1].(*models.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepo_Create_Call) Return(err error) *MockClientRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepo_Create_Call) RunAndReturn(run func(ctx context.Context, c *models.Client) error) *MockClientRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockClientRepo
func (_mock *MockClientRepo) GetByID(ctx context.Context, id string) (*models.Client, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Client, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Client); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClientRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClientRepo_Expecter) GetByID(ctx any, id any) *MockClientRepo_GetByID_Call {
	return &MockClientRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockClientRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockClientRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepo_GetByID_Call) Return(client *models.Client, err error) *MockClientRepo_GetByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Client, error)) *MockClientRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepo creates a new instance of MockRefreshTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRefreshTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRefreshTokenRepo is an autogenerated mock type for the refreshTokenRepo type
type MockRefreshTokenRepo struct {
	mock.Mock
}

type MockRefreshTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepo_Expecter {
	return &MockRefreshTokenRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) Create(ctx context.Context, t *models.RefreshToken) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RefreshToken) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *models.RefreshToken
func (_e *MockRefreshTokenRepo_Expecter) Create(ctx any, t any) *MockRefreshTokenRepo_Create_Call {
	return &MockRefreshTokenRepo_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockRefreshTokenRepo_Create_Call) Run(run func(ctx context.Context, t *models.RefreshToken)) *MockRefreshTokenRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*models.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Create_Call) Return(err error) *MockRefreshTokenRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_Create_Call) RunAndReturn(run func(ctx context.Context, t *models.RefreshToken) error) *MockRefreshTokenRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenByHash provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) GetTokenByHash(ctx context.Context, hash string) (*models.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenByHash")
	}

	var r0 *models.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepo_GetTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenByHash'
type MockRefreshTokenRepo_GetTokenByHash_Call struct {
	*mock.Call
}

// GetTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepo_Expecter) GetTokenByHash(ctx any, hash any) *MockRefreshTokenRepo_GetTokenByHash_Call {
	return &MockRefreshTokenRepo_GetTokenByHash_Call{Call: _e.mock.On("GetTokenByHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepo_GetTokenByHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepo_GetTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_GetTokenByHash_Call) Return(refreshToken *models.RefreshToken, err error) *MockRefreshTokenRepo_GetTokenByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepo_GetTokenByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*models.RefreshToken, error)) *MockRefreshTokenRepo_GetTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSessionRepo is an autogenerated mock type for the sessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Create(ctx context.Context, userID string, email string) (string, time.Time, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, time.Time, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) time.Time); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, userID, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
func (_e *MockSessionRepo_Expecter) Create(ctx any, userID any, email any) *MockSessionRepo_Create_Call {
	return &MockSessionRepo_Create_Call{Call: _e.mock.On("Create", ctx, userID, email)}
}

func (_c *MockSessionRepo_Create_Call) Run(run func(ctx context.Context, userID string, email string)) *MockSessionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Create_Call) Return(s string, time1 time.Time, err error) *MockSessionRepo_Create_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *MockSessionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, email string) (string, time.Time, error)) *MockSessionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Destroy(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockSessionRepo_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepo_Expecter) Destroy(ctx any, sessionID any) *MockSessionRepo_Destroy_Call {
	return &MockSessionRepo_Destroy_Call{Call: _e.mock.On("Destroy", ctx, sessionID)}
}

func (_c *MockSessionRepo_Destroy_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepo_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Destroy_Call) Return(err error) *MockSessionRepo_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Destroy_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionRepo_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Get(ctx context.Context, sessionID string) (*models.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepo_Expecter) Get(ctx any, sessionID any) *MockSessionRepo_Get_Call {
	return &MockSessionRepo_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *MockSessionRepo_Get_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Get_Call) Return(session *models.Session, err error) *MockSessionRepo_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepo_Get_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*models.Session, error)) *MockSessionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthCodeRepo creates a new instance of MockAuthCodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthCodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthCodeRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthCodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthCodeRepo is an autogenerated mock type for the authCodeRepo type
type MockAuthCodeRepo struct {
	mock.Mock
}

type MockAuthCodeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthCodeRepo) EXPECT() *MockAuthCodeRepo_Expecter {
	return &MockAuthCodeRepo_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockAuthCodeRepo
func (_mock *MockAuthCodeRepo) Consume(ctx context.Context, code string) (*models.AuthCode, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 *models.AuthCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.AuthCode, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.AuthCode); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthCodeRepo_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockAuthCodeRepo_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockAuthCodeRepo_Expecter) Consume(ctx any, code any) *MockAuthCodeRepo_Consume_Call {
	return &MockAuthCodeRepo_Consume_Call{Call: _e.mock.On("Consume", ctx, code)}
}

func (_c *MockAuthCodeRepo_Consume_Call) Run(run func(ctx context.Context, code string)) *MockAuthCodeRepo_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthCodeRepo_Consume_Call) Return(authCode *models.AuthCode, err error) *MockAuthCodeRepo_Consume_Call {
	_c.Call.Return(authCode, err)
	return _c
}

func (_c *MockAuthCodeRepo_Consume_Call) RunAndReturn(run func(ctx context.Context, code string) (*models.AuthCode, error)) *MockAuthCodeRepo_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAuthCodeRepo
func (_mock *MockAuthCodeRepo) Create(ctx context.Context, data models.AuthCode) (string, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AuthCode) (string, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AuthCode) string); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.AuthCode) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthCodeRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthCodeRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.AuthCode
func (_e *MockAuthCodeRepo_Expecter) Create(ctx any, data any) *MockAuthCodeRepo_Create_Call {
	return &MockAuthCodeRepo_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockAuthCodeRepo_Create_Call) Run(run func(ctx context.Context, data models.AuthCode)) *MockAuthCodeRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AuthCode
		if args[1] != nil {
			arg1 = args[1].(models.AuthCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthCodeRepo_Create_Call) Return(s string, err error) *MockAuthCodeRepo_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthCodeRepo_Create_Call) RunAndReturn(run func(ctx context.Context, data models.AuthCode) (string, error)) *MockAuthCodeRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTokenIssuer is an autogenerated mock type for the tokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function for the type MockTokenIssuer
func (_mock *MockTokenIssuer) IssueAccessToken(userID string, email string) (*models.AccessToken, error) {
	ret := _mock.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 *models.AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*models.AccessToken, error)); ok {
		return returnFunc(userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *models.AccessToken); ok {
		r0 = returnFunc(userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenIssuer_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type MockTokenIssuer_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - userID string
//   - email string
func (_e *MockTokenIssuer_Expecter) IssueAccessToken(userID any, email any) *MockTokenIssuer_IssueAccessToken_Call {
	return &MockTokenIssuer_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", userID, email)}
}

func (_c *MockTokenIssuer_IssueAccessToken_Call) Run(run func(userID string, email string)) *MockTokenIssuer_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenIssuer_IssueAccessToken_Call) Return(accessToken *models.AccessToken, err error) *MockTokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *MockTokenIssuer_IssueAccessToken_Call) RunAndReturn(run func(userID string, email string) (*models.AccessToken, error)) *MockTokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function for the type MockTokenIssuer
func (_mock *MockTokenIssuer) IssueRefreshToken() (string, time.Time) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 time.Time
	if returnFunc, ok := ret.Get(0).(func() (string, time.Time)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() time.Time); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	return r0, r1
}

// MockTokenIssuer_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockTokenIssuer_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
func (_e *MockTokenIssuer_Expecter) IssueRefreshToken() *MockTokenIssuer_IssueRefreshToken_Call {
	return &MockTokenIssuer_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken")}
}

func (_c *MockTokenIssuer_IssueRefreshToken_Call) Run(run func()) *MockTokenIssuer_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenIssuer_IssueRefreshToken_Call) Return(s string, time1 time.Time) *MockTokenIssuer_IssueRefreshToken_Call {
	_c.Call.Return(s, time1)
	return _c
}

func (_c *MockTokenIssuer_IssueRefreshToken_Call) RunAndReturn(run func() (string, time.Time)) *MockTokenIssuer_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
